### ISSUE TITLE
Iterate over variants with default values

### ISSUE THREAD

**Issue by nielsle** [stephaneyfx/enum-iterator#4]
Just an idea. It could be useful to iterate over variants of an enum, if all variants have a default value. It could work like this
~~~ rust
use ambassador::{delegatable_trait, Delegate};

#[delegatable_trait]
trait Animal {
    fn leg_count(&self) -> u16 {}
}

#[derive(Default)]
struct Chicken;
impl Animal for Chicken {
    fn leg_count(&self) -> u16 {  2 }
}

#[derive(Default)]
struct Sheep;
impl Animal for Sheep {
    fn leg_count(&self) -> u16 { 4 }
}

#[derive(IntoEnumIterator)]
#[delegate(Animal)]
enum AnimalKind {
    Chicken(Chicken),
    Sheep(Sheep),
}

fn main() {
    for animal in AnimalKind::into_enum_iter() {
        println!("This animal has {} legs!", animal.leg_count());
    }
}
~~~

Inspired by
https://github.com/rust-lang/rfcs/pull/2874

**Comment by stephaneyfx** [comment]
Thank you for the detailed write-up!

The goal of this crate is to provide an iterator over _all_ possible values of an enumeration type. As soon as variants can have data attached to them, this becomes more complex. For example, let's consider the following enumeration:

```rust
enum Foo {
    A,
    B(u8),
}
```

I would expect `Foo::into_enum_iter()` to return an iterator that yields `Foo::A`, `Foo::B(0)`, `Foo::B(1)`, ..., `Foo::B(255)`, so that _all_ possible values of the type are yielded.

Some other crates like [strum](https://github.com/Peternator7/strum/wiki/Derive-EnumIter) support such a use case and only return `Foo::B(0)` (`Default::default()` of the data type), but what do such iterators really mean? They only yield an arbitrary subset of the possible values of the enumeration, and I don't find that particularly useful, but it might just be that I haven't seen a concrete use case for it yet (concrete as in practical, that showed up when developing some application).

So I want to say that this is not supported by design. However I am open to changing my mind if given convincing, practical examples showing how supporting this use case helps.

**Comment by nielsle** [comment]
Thank you for your answer. I will have a look at strum.
